### ISSUE TITLE
Implement NiMARE IBMA estimators in PyMARE

### ISSUE THREAD

**Issue by tsalo** [neurostuff/PyMARE#16]
- Fisher's
- Stouffer's (t-test on z-statistics)
- Stouffer's with empirical null distribution (null derived from sign flipping)
- Weighted Stouffer's
- RFX GLM (t-test on estimates)
- RFX GLM with empirical null distribution (null derived from sign flipping)

**Comment by tyarkoni** [comment]
I'm working on this now. I'm on board with adding Stouffer's, but I don't think we need the others:

* The "RFX GLM" is unnecessary because we already have a `WeightedLeastSquares` estimator that defaults to OLS if no variances are passed (well, it doesn't currently, but it's about to), and I believe that's identical to the proposal here.
* Fisher's seems to me to have little utility because it produces p-values very similar to Stouffer's under most circumstances, and unlike Stouffer's, doesn't allow for weights. Given that both methods are pretty much a Hail Mary you'd only use if you have nothing but p/z values available, I don't see much benefit in providing multiple options.
* We get permutation testing for free, because it's implemented in a completely generic way (you can take any `MetaRegressionResults` instance and pass it to `permutation_test()`).

Does that sound reasonable, @tsalo, @nicholst?

**Comment by nicholst** [comment]
Agree about RFX GLM, but Fisher’s is really ubiquitous... I won’t drop it. (You can find generalizations that include weights, if that’s the key thing).  In my experience it can be a touch better than Stouffer's as it can be driven by a handful of strong results. (I know,  not usually a feature, but in the FFX world that’s Ok).

**Comment by tyarkoni** [comment]
Okay, will add it as well. Thanks for the quick feedback!
