### ISSUE TITLE
CombinationTest p-values incorrect

### ISSUE THREAD

**Issue by tsalo** [neurostuff/PyMARE#36]
I am working on a more comprehensive example for Estimators, and I noticed that the p-value for Stouffer's results was close to 1.0, even though I don't think it should be.

Please see [this notebook](https://github.com/tsalo/misc-notebooks/blob/1bbde1d2f63adb0e09c1afa2cf0fc97e3e9b4198/pymare_example.ipynb) for the code used to see this.

EDIT: To summarize the thread below- the p-values are being set, but they're incorrect. We just need to change the `scipy.stats` function used to calculate the p-values to fix the bug.

**Comment by tyarkoni** [comment]
I'll take a look, but I think that may be right, subject to loss of precision. The p-value is two-sided, so you can think of it as p = 0, where z > 0. Of course it isn't really zero, it should be some very small number. But many of scipy's stats functions aren't very good about preserving precision, and given a z of 24, I'm not surprised you get a result of `1.0`.

**Comment by tyarkoni** [comment]
BTW, in case you're wondering why we don't just return two-tailed p-values (i.e., `0` when z is both positive and negative), it's because for the Stouffer and Fisher estimators, there's no information other than p and z to work with. Given that you can pass in p-values as inputs, it's essential to preserve tail information. This is a bit unfortunate given that it deviates from the p-values returned by other estimators, but I don't see a good way around it. We could maybe make it clearer in the docs though.

**Comment by tsalo** [comment]
I think I must have just misunderstood the test. 

In the absence of weights (`v`), and using z-values instead of p-values, the test first calculates the FFX stat as `sum(input) / sqrt(n_inputs)`, and then uses `scipy.stats.norm.cdf` to get the associated right-sided p-value. So if the FFX stat is 1.65, the estimator's p-value is ~0.95.

Isn't the purpose of the test to see if the FFX stat is significantly different from 0, so shouldn't it use `scipy.stats.norm.sf` instead? So that a FFX stat of 1.65 would be ~0.05? Or `scipy.stats.norm.cdf` on the negative FFX stat I guess (which is what NiMARE does).

**Comment by tyarkoni** [comment]
Actually, using `sf` probably makes sense for the sake of improved precision (ironically, I had already switched from `cdf` to `sf` for this reason in `MetaRegressionResults.get_fe_stats()`, I just didn't do it for `CombinationTestResults.p()`). But it won't solve the issue you're raising, because `sf` is just `1 - cdf`, so if your z score had been `-24`, you would just end up with p ~ 1.0, which is probably not what you want either.

The issue here is really one of user experience. We can of course easily return two-sided p-values (i.e., p = .05 for both z = 1.96 and z = -1.96). The concern is that this could easily mislead people into thinking that the p/z values passed as inputs to these estimators can/should *also* be two-sided. And it's pretty essential that p inputs be one-tailed when possible (by default, right-tailed), otherwise you're testing a really weird null (roughly, "do studies differ from zero on average, irrespective of sign").

Two other possible approaches:
* Stipulate that users can only pass z-scores as inputs, and disallow p values. That would remove most of the ambiguity. But it would deviate from most of the R implementations, which tend to take p-value rather than z-score inputs, and potentially force users to do extra conversions on their side, decreasing usability.
* Add a `two_tailed` initialization argument to `CombinationTestResults` that controls the behavior. That's probably worth doing anyway, but I don't know how much it would help, as the results object is typically generated implicitly, so I think getting the default right is pretty important.

@nicholst, any thoughts?

**Comment by nicholst** [comment]
Hi @tyarkoni @tsalo,

Firstly, in the notebook
```
z: 6.023224917324951
p: 0.999999999145122
```
this is just an error, unless we intended to implement one-sided left-tailed p-value.

Secondly, I think the fundamental issue Anderson tackled very nicely in his [Combining paper's Figure 3](https://pubmed.ncbi.nlm.nih.gov/26848101/#&gid=article-figures&pid=figure-3-uid-2). 

In short, he distinguished combining directed (one-sided), non-directed (two-sided) and concordant hypotheses.  One-sided and two-sided are as you know them; concordant means "I am interested in either increases or decreases, but I only care about the results when all directions are consistent.   To do concordant testing you two the combing procedure twice, once with with left-tailed one-sided, once with right-tailed one-sided and then correct for doing two tests (you can double the p-value or, as PALM does, let the permutation distribution account for the multiplicity).  This concordant method sounds hacky but has a long history; see Owen (2009).

So!  For Fisher's and Stouffer's I'd say we follow PALM's lead and offer:  one-sided (assumed right-tail), two-sided and concordant modes.

Stouffer's
* one-sided: p-values are converted to Z's with `scipy.stats.norm.isf`, with p=0 going to predefined MAX_Z, p=1 - MAX_Z; t-values converted with probability integral transform, i.e. `scipy.stats.norm.isf(scipy.stats.t.sf(t,df))`; z values taken directly.
* two-sided: p-values are converted as one-sided; t-values converted with`scipy.stats.norm.isf(2*scipy.stats.t.sf(np.abs(t),df))`; z values are used as `np.abs(z)`.
* concordant: (Must assume one-sided p-values computed). Two one-sided analyses conducted: one with p, t or z as delivered, one with 1-p, -t or -z as delivered.

Fisher's
* one-sided: p-values taken as is, with p=0 remapped to MIN_P; t-values converted to p with `scipy.stats.t.sf(t,df)`; z converted with `scipy.stats.norm.sf(z)`.
* two-sided: p-values taken as is, with p=0 remapped to MIN_P; t-values converted with`2*scipy.stats.t.sf(np.abs(t),df)`; z values with`2*scipy.stats.norm.sf(np.abs(t),df)`.
* concordant: (Must assume one-sided p-values computed). Two one-sided analyses conducted: one with p, t or z as delivered, one with 1-p, -t or -z as delivered.

Note for the "two-sided" cases above I was trusting that the p-value was properly computed from a two-sided test.  If we want to accept a p-value from a one-sided test for "two-sided" mode, we need to remap them as `p_twosided = np.max(2*p_onesided,1)`.

How does this sound?

### Reference

Owen, A. B. (2009). Karl Pearson’s meta-analysis revisited. The Annals of Statistics, 37(6B), 3867–3892. https://doi.org/10.1214/09-AOS697

**Comment by nicholst** [comment]
I just realised that I had an error in my comment... I said two-sided Stouffer's takes Z's by just doing `np.abs(z)` but that's wrong... you can't can't truncate Z values like that ... you have to map them into all possible z's (-inf,inf), just like is done for t-values.  I've edited the comment above to fix this.

**Comment by tsalo** [comment]
Thanks @nicholst! So, in terms of the `p_type` argument, it seems like it's a matter of a small bug fix. I can open a PR with that soon.

You're also proposing that we add a new argument (e.g., `mode`) to determine the hypothesis to be tested, correct? I can take a crack at that, although I'll probably split the changes into two PRs and create a separate issue as well.

The other thing you mentioned that stuck out to me is t-values. From the way it's currently set up (i.e., for p- and z-values only), I assume that users are expected to convert any t-values to p or z beforehand. Do you want explicit t-value support, or are you okay with assuming that data have already been converted?

**Comment by nicholst** [comment]
Hi @tsalo, yes, I guess letting the function know the type of p-value is crucial, and agree `mode` is a new argument to add.

About t vs z, I'm not too fussed.  I thought accepting t's would be a helpful service, but it's trivial for a user to do if we don't want to add it.  Thoughts, @tyarkoni ?

**Comment by tyarkoni** [comment]
The above all makes sense to me, and I like the idea of adding a concordant mode. But I'm still concerned about confusion on the user's part as a result of having to separately specify both the type of p-value being passed as input, and the mode of the test being performed. The mapping is kind of messy, in that if you start with one-sided p-values, you're constrained to a one-sided combination test, but if you start with two-sided p-values, you can select whatever mode you like. I'd like to say that users can *only* pass two-sided p-values in, but that would be kind of restrictive, as it would mean that data points that came from a one-sided analysis (where the user has no access to the original stats) can't be included.

@tsalo maybe hold off on implementing the `mode` argument. I'm not entirely satisfied with the way the `CombinationTest` classes are set up, especially in relation to `CombinationTestResults`, so I might rework this some.

**Comment by tsalo** [comment]
@tyarkoni That works for me. I spent some time yesterday trying to figure out how to implement it all and kept coming up against weird behaviors, so I'm happy to walk away from it for awhile.

**Comment by nicholst** [comment]
OK... sounds like you have API work to do... let me know if I can weigh in.

But just to clarify: *concordant* mode only makes sense for one-sided p-values.  Concordance doesn't make sense for two-sided (you'd never check for two-sided p-values being consistently near 1, as that simply means the effect was near 0, not showing evidence of an effect in the other direction).

**Comment by tyarkoni** [comment]
@nicholst argh, yes, sorry, I keep getting tripped up on this. I was also wrong about two-sided p-values being compatible with any mode; they're actually pretty worthless if passed in as input, because the only null you can test is the weird one I mentioned earlier in the thread. It's actually one-sided p-values that we want as input. I think what keeps tripping me up is that for the combination tests, there's no parameter estimate we can refer to in order to determine the original sign of effect (otherwise it would be trivial to convert two-sided p to one-sided if the user wants a one-sided test).

The more I think about it, the more convinced I am that allowing p-value inputs is going to be a bit of a UX nightmare. I find it just really counterintuitive to insist on users passing in one-tailed p-values given that by default, we return two-sided p-values pretty much everywhere else. I'm wondering if maybe we should actually only allow z-scores as input. This would introduce an extra step for users, but I suspect that in the process of converting p to z, a lot of users who happen to be working with two-sided p-values would realize that they need to take extra steps to recover the original sign, whereas they might otherwise just pass them in blindly without thinking about it. And in the case where users already have z-scores, they're almost certainly properly two-sided (as opposed to being naively converted from p-values). WDYT?

**Comment by nicholst** [comment]
Yes, I think forbidding p-values as input is a good idea... too much ambiguity and potential precision loss.

Then there is the issue if you're going to allow z and t.  Seems like a small pain to require users to map from t to z, but not a huge issue.  If we accept t, then do flag the issue that (someday) the DF might be voxel-varying.

**Comment by tyarkoni** [comment]
@nicholst I'm finally getting around to implementing these tests as per your [comment above]([here](https://github.com/neurostuff/PyMARE/issues/36#issuecomment-643081860) and Winkler et al. (2016), and it all seems to be working nicely, except that I'm currently having second thoughts about whether it's a good idea to support the two-sided mode in the meta-analysis context.

I get that this is a perfectly valid null to test, and I can think of cases where it would be what you want—e.g., in a scenario where you're combining p-values from two very different kinds of contrasts, and you're asking, roughly, "does this brain region seem to be associated with these two contrasts in any meaningful way, ignoring sign in each case." But the overwhelming use case in meta-analysis seems to me to be that you assume all of the estimates are drawn from the same population (roughly), and you're testing for consistent deviations of the mean from 0. In this case, the one-sided and concordant tests make perfect sense, and so does a two-tailed version of the one-sided test (i.e., just the standard transformation of the resulting p-value), but the two-sided test is something you would almost never want to do, as it is, in a sense, testing a hypothesis about the variance of the estimates rather than their mean.

In principle there's nothing wrong with supporting functionality that almost no one uses, but in this case we're going to have an initialization call that looks something like `estimator = Stouffer(mode='one-sided')`, and I think it's a foregone conclusion that many people won't read the docstring (or even warning) carefully enough to realize that two-sided in this context means something very different from two-tailed, and will then pass 'two-sided' naively thinking they're jus doing a two-tailed version of whatever procedure they're invoking . So I can easily envision a bunch of very broken results being reported in papers.

Do you have any strong attachment to the two-sided mode, or can we just drop it? I you do want to keep it, do you have suggestions for an interface that might discourage people from doing bad things? E.g., it's a bit clunky, but we could potentially have a separate set of classes (e.g., `TwoSidedStouffer` etc.), though I'm not sure that will prevent catastrophe either. Maybe we can have a `i_understand_what_directionless_means_in_this_context_and_accept_the_consequences=True` flag...

**Comment by nicholst** [comment]
Hey @tyarkoni,

The compelling use case for the two-sided mode is combining across SNP associations:  If I have, say, 10 T-maps based on 10 SNP-Brain associations, I have no way of knowing a priori whether the rare or common allele is the 'risk' allele, and thus you use this approach to combine any and all information.  HOWEVER, that use case really isn't applicable here because that's where the 10 maps all arose from the *same* brain data, and you use a synchronised permutation approach.  So it's a "meta combining" approach applied on a single response dataset.

But riffing on that, couldn't we imagine a case where I've got a bucket of heterogeneous association studies... say, GM thickness or VBM, in a wide mix of studies that considered different lifestyle factors.  Now *mostly* you'd expect people would know which is the 'risk' direction of a lifestyle factor, but maybe it's conceivable that the "risky" or "protective" direction is unclear?  (Moderate drinking's supposed positive effects on cardiovascular health is one such thing that comes to mind).

So!  Unless it's a pain to support, I would keep it, but certainly not make it easy to activate accidentally.  I'm too far from the code structure to know how, but indeed, something like `TwoSidedStouffer="Yes,Really"` should be enough.

**Comment by tyarkoni** [comment]
Okay, I'll keep it then (it's already implemented, so not a pain at all to support).

To minimize abuse, I think I'll go with the following approach: (a) have the modes be called 'directed', 'non-directed', and 'concordant', which should hopefully already combat the proclivity to select "two-sided" to some degree, and (b) if the user selects 'non-directed', raise an error that requires them to set a package-level setting called `AllowNonDirected` or something like that.

**Comment by tsalo** [comment]
> (b) if the user selects 'non-directed', raise an error that requires them to set a package-level setting called AllowNonDirected or something like that.

Would it be enough to include a warning section in the docstring and maybe log a warning if `mode="non-directed"`?

**Comment by tyarkoni** [comment]
> Would it be enough to include a warning section in the docstring and maybe log a warning if mode="non-directed"?

Maybe... I'm *very* nervous about this. I just don't see many scenarios in which someone will have a legitimate use for an undirected test and still be using pymare/nimare (the use cases @nicholst mentions are all valid, but I think the probability of someone looking to conduct those kinds of tests will happen upon these packages is low; most likely they'll just use PALM). But I guess we can start out that way and beef things up later if it becomes a problem.

**Comment by tyarkoni** [comment]
@nicholst, one more implementation question. You write:

> Note for the "two-sided" cases above I was trusting that the p-value was properly computed from a two-sided test. If we want to accept a p-value from a one-sided test for "two-sided" mode, we need to remap them as p_twosided = np.max(2*p_onesided,1).

We're only accepting z-score inputs now, but just to make sure I have it right, the z-scores passed in should always correspond to *one*-sided p-values, right? Even when `mode='undirected'`? Otherwise the `abs()` step seems weird, as the inputs already lack sign information, and we'd now be treating p-values close to 0.5 as equivalent to those close to 0. So I'm assuming we only want to accept z-scores that come from one-tailed procedures, for all modes. But maybe I'm misunderstanding.

**Comment by nicholst** [comment]
On error vs warning, I'm with @tyarkoni for making it an error unless a flag has been set somewhere.

And on z-scores, yes, of course, a z-score is a z-score, with direction.  I was trying to map out what happens with p-value inputs, but that's not relevant apparently.

**Comment by tyarkoni** [comment]
While we're on the topic of p-values, I've been thinking about what kind of p-value we want the combination tests to return, and it turns out to be not so straightforward (or at least, doesn't seem so to me). In the case of concordant and undirected tests, it's a non-issue, as these nulls are non-directional. But in the case of a directed test, which is the default, it would seem natural to return a one-tailed p-value... except that that would introduce several complications:

1. Returning one-tailed p by default is inconsistent with the default for other estimators, which return two-sided p-values (actually, they don't right now, but they will shortly). If we leave "directed" mode as the default for the combination tests, people will be getting back one-tailed p-values, probably without realizing it.
2. It would still be unclear whether we should return left-tailed p-values or something different. I looked at PALM for inspiration, but it does something I find pretty unintuitive, which is that it always returns the p-value for the direction that favors the alternative hypothesis (i.e., you can't tell from the p-value whether mu < 0 or mu > 0). This wouldn't be much of an issue in the context of tests where there's some readily available point estimate that conveys sign information, but in the case of combination tests, it seems plausible that users often won't actually know (at least, not without doing some extra work) whether the p-value corroborates or disconfirms their hypothesis. If we always report the "good" direction, I think there's a risk of people uncritically assuming anything < .05 is consistent with their hypothesis, and reporting it as such.
3. If we were to give users control over whether directed tests return one-tailed or two-tailed p-values, we would be adding a whole other level of confusion: users might naively expect "two-tailed directed test" to mean the same thing as "undirected" test, but in this context, these are very different things (they test completely different nulls). When you add in the fact that the "concordant" mode is actually conceptually pretty close (but still not identical) to the two-tailed directed test, it becomes even messier. So I think I'd really rather avoid having separate `mode` and `alternative` arguments users can control.

I guess my fairly strong temptation here is to bite the bullet and only return two-tailed p-values throughout the package, including for "directed" combination tests (which is currently the default mode). If you a user wants one-tailed p-values, they can of course just halve the observed p-value—but at least then it's on them to figure out which tail they should be looking at. We would need to explain this clearly in the docstrings, especially in the case of the combination tests, but in general it seems safer to return conservative p-values and risk users underselling their results than to basically ~double the chance an uncritical user is going to get a result they like. And it would mean users get consistent (two-tailed) p-values everywhere in the package, by default.

What do you think?

**Comment by nicholst** [comment]
OK... happy to discuss p-values.  While I'm all for encouraging a move away from one-sided as default, it seems we'll always need to have options to have one-sided.

And, btw, what you described in your original comment (before editing) is I think Owen's method he attributes to Pearson, where you pick the direction that is most favourable for each test.  It makes sense for genetics where the risk allele is unknown, but I've never been tempted to use it in brain imaging since you'll have different collections of signs at each voxel.

Owen, A. B. (2007). Pearson’s Test in a Large Scale Multiple. Retrieved from https://statweb.stanford.edu/~owen/reports/pearsonmeta.pdf

Owen, A. B. (2009). Karl Pearson’s meta-analysis revisited. The Annals of Statistics, 37(6B), 3867–3892. https://doi.org/10.1214/09-AOS697
