### ISSUE TITLE
Extra Dimension in output?

### ISSUE THREAD

**Issue by jdkent** [neurostuff/PyMARE#60]
ref neurostuff/nimare#449

opening this issue to follow up from NiMARE to see if this behavior is expected in PyMARE.

**Comment by tyarkoni** [comment]
I assume the 4th dimension in NiMARE is being carried over from a reshaping from 2d, or something, but yes, it is the case that PyMARE internally uses 2d for estimates. This is because the 2nd dimension is for parallel datasets (mainly useful for algorithms that can be vectorized). So the expectation would be that NiMARE passes voxels in that second dimension, and then reshapes back to 3d on the return.
